# GoFrame CLI tool configuration.
gfcli:
  gen:
    dao:
      - link: "mysql:gostudy:123456@tcp(127.0.0.1:3306)/takeaway"
        removePrefix: "gf_"
        descriptionTag: true
        noModelComment: true
