// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package takeaway

import (
	"github.com/gogf/gf-demo-user/v2/api/takeaway"
)

type ControllerV2 struct{}

func NewV2() takeaway.ITakeawayV2 {
	return &ControllerV2{}
}
